// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {moviedownloader} from '../models';

export function SaveEndpoint(arg1:string):Promise<Error>;

export function Search(arg1:string):Promise<moviedownloader.SearchResponse|Error>;

export function Complete(arg1:number):Promise<Error>;

export function Download(arg1:string):Promise<Error>;

export function GetEndpoint():Promise<string>;
