// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Complete(arg1) {
  return window['go']['main']['App']['Complete'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function GetEndpoint() {
  return window['go']['main']['App']['GetEndpoint']();
}

export function SaveEndpoint(arg1) {
  return window['go']['main']['App']['SaveEndpoint'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
