// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Complete(arg1:number):Promise<void>;

export function Download(arg1:string):Promise<void>;

export function GetEndpoint():Promise<string>;

export function SaveEndpoint(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<any>;
